CREATE TABLE [dbo].[DataTypeTestNullable]
(
	[DataTypeTestNullableId] INT IDENTITY(1,1) NOT NULL,
	[Int64] BIGINT NULL,
	[ByteArray_Binary] BINARY(10) NULL,
	[Boolean] BIT NULL,
	[String_Char] CHAR(1) NULL,
	[DateTime_Date] DATE NULL,
	[DateTime_DateTime] DATETIME NULL,
	[DateTime_DateTime2] DATETIME2(0) NULL,
	[DateTimeOffset] DATETIMEOFFSET NULL,
	[Decimal_Decimal] DECIMAL(4,2) NULL,
	[Double] FLOAT NULL,
	[Int32] INT NULL,
	[Decimal_Money] MONEY NULL,
	[String_NChar] NCHAR(1) NULL,
	[Decimal_Numeric] NUMERIC(4,2) NULL,
	[String_NVarchar] NVARCHAR(10) NULL,
	[Single] REAL NULL,
	[ByteArray_RowVersion] ROWVERSION NULL,
	[DateTime_SmallDateTime] SMALLDATETIME NULL,
	[Int16] SMALLINT NULL,
	[Decimal_SmallMoney] SMALLMONEY NULL,
	[TimeSpan] TIME NULL,
	[Byte] TINYINT NULL,
	[Guid] UNIQUEIDENTIFIER NULL,
	[ByteArray_VarBinary] VARBINARY(10) NULL,
	[String] VARCHAR(10) NULL,
	[Xml] XML NULL,
	CONSTRAINT [PK_dbo.DataTypeTestNullable_DataTypeTestNullableId] PRIMARY KEY ([DataTypeTestNullableId])
)
