CREATE TABLE [dbo].[DataTypeTest]
(
	[DataTypeTestId] INT IDENTITY(1,1) NOT NULL,
	[Int64] BIGINT NOT NULL,
	[ByteArray_Binary] BINARY(10) NOT NULL,
	[Boolean] BIT NOT NULL,
	[String_Char] CHAR(1) NOT NULL,
	[DateTime_Date] DATE NOT NULL,
	[DateTime_DateTime] DATETIME NOT NULL,
	[DateTime_DateTime2] DATETIME2(0) NOT NULL,
	[DateTimeOffset] DATETIMEOFFSET NOT NULL,
	[Decimal_Decimal] DECIMAL(4,2) NOT NULL,
	[Double] FLOAT NOT NULL,
	[Int32] INT NOT NULL,
	[Decimal_Money] MONEY NOT NULL,
	[String_NChar] NCHAR(1) NOT NULL,
	[Decimal_Numeric] NUMERIC(4,2) NOT NULL,
	[String_NVarchar] NVARCHAR(10) NOT NULL,
	[Single] REAL NOT NULL,
	[ByteArray_RowVersion] ROWVERSION NOT NULL,
	[DateTime_SmallDateTime] SMALLDATETIME NOT NULL,
	[Int16] SMALLINT NOT NULL,
	[Decimal_SmallMoney] SMALLMONEY NOT NULL,
	[TimeSpan] TIME NOT NULL,
	[Byte] TINYINT NOT NULL,
	[Guid] UNIQUEIDENTIFIER NOT NULL,
	[ByteArray_VarBinary] VARBINARY(10) NOT NULL,
	[String] VARCHAR(10) NOT NULL,
	[Xml] XML NOT NULL,
	CONSTRAINT [PK_dbo.DataTypeTest_DataTypeTestId] PRIMARY KEY ([DataTypeTestId])
)
